---
etcd_cluster_name: "k8s-etcd-cluster"
etcd_initial_cluster: >-
  {% for host in groups['etcd'] -%}
  {{ host }}=https://{{ hostvars[host]['ip'] }}:2380{% if not loop.last %},{% endif %}
  {%- endfor %}