# prompt for list of hosts to patch 
- debug:
    msg: "Patching OS on {{ inventory_hostname }}"

- name: Update package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install only security updates
  ansible.builtin.apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes

- name: Reboot if a security kernel update was applied
  ansible.builtin.reboot:
