---
- name: Prompt for hosts and run roles
  hosts: localhost  # Runs locally to capture user input
  gather_facts: false
  vars_prompt:
    - name: target_hosts
      prompt: "Enter the target hosts (comma-separated or pattern like webservers)"
      private: false  # Shows input in terminal

  tasks:
    - name: Set dynamic hosts
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: dynamic_target
      loop: "{{ target_hosts.split(',') | map('trim') | list }}"

- name: Remove workers
  hosts: dynamic_target
  become: true
  tasks:
    - name: Scale Down Worker
      ansible.builtin.include_role:
        name: common
        tasks_from: patch-os.yaml
