# install calico cni
# - name: Install Calico CNI
#   ansible.builtin.shell: |
#     export KUBECONFIG=/opt/kubernetes/.kube/config
#     kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
#   args:
#     creates: /opt/kubernetes/calico_installed
#   tags: install_calico

- name: Create calico.yaml file
  ansible.builtin.copy:
    src: addons/calico.yaml
    dest: /opt/kubernetes/calico.yaml
    mode: "0644"
  tags: install_calico


- name: Deploy calico with Helm
  kubernetes.core.helm:
    name: projectcalico
    chart_ref: tigera-operator
    chart_version: v3.28.2
    chart_repo_url: https://docs.tigera.io/calico/charts
    release_namespace: tigera-operator
    create_namespace: true
    values_files:
      - /opt/kubernetes/calico.yaml
    kubeconfig: /opt/kubernetes/.kube/config
  tags: install_calico
