# install cilium

# install cni cilium with helm
- name: Deploy Cilium with Helm
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium
    chart_version: 1.16.6
    chart_repo_url: https://helm.cilium.io/
    release_namespace: kube-system
    create_namespace: true
    kubeconfig: /opt/kubernetes/.kube/config
  tags: install_cilium

- name: Get the latest Cilium CLI version
  ansible.builtin.uri:
    url: "https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt"
    return_content: true
  register: cilium_cli_version
  changed_when: false
  tags: install_cilium

- name: Set CLI architecture based on the system
  ansible.builtin.set_fact:
    cli_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
  tags: install_cilium

- name: Download Cilium CLI tar and checksum files
  ansible.builtin.get_url:
    url: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version.content }}/cilium-linux-{{ cli_arch }}.tar.gz{{ item }}"
    dest: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz{{ item }}"
    mode: "0644"
  loop:
    - ""
    - ".sha256sum"
  tags: install_cilium

- name: Verify Cilium CLI checksum
  ansible.builtin.command:
    cmd: "sha256sum --check /tmp/cilium-linux-{{ cli_arch }}.tar.gz.sha256sum"
    chdir: /tmp
  register: checksum_result
  failed_when: checksum_result.rc != 0
  tags: install_cilium

- name: Extract Cilium CLI to /usr/local/bin
  ansible.builtin.unarchive:
    src: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz"
    dest: "/usr/local/bin"
    remote_src: true
  tags: install_cilium

- name: Clean up Cilium CLI tar and checksum files
  ansible.builtin.file:
    path: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz{{ item }}"
    state: absent
  loop:
    - ""
    - ".sha256sum"
  tags: install_cilium
