---
- name: Compare resources
  ansible.builtin.import_tasks: compare-node.yaml
  when: inventory_hostname == groups['masters'][0]

- name: Check if resources are in sync
  fail:
    msg: "All resources are synced"
  when: hostvars[groups['masters'][0]]['nodes_to_add'].stdout == "[]" and hostvars[groups['masters'][0]]['nodes_to_remove'].stdout == "[]"
  run_once: true
  delegate_to: localhost

- name: Confirm control-plane nodes are odd
  fail:
    msg: "Control-plane nodes must be odd"
  when: (groups['masters'] | length) % 2 == 0
  run_once: true
  delegate_to: localhost

- pause:
    prompt: "Do you want to apply the above changes? (Y/n)"
  register: my_pause
  delegate_to: localhost
  run_once: true

- name: Confirm sync changes
  fail:
    msg: "Maybe in the next life"
  when: my_pause.user_input|lower != 'y'
  run_once: true

#scale up

- name: Prepare node
  ansible.builtin.import_tasks: prepare-nodes.yaml
  tags: prepare-nodes
  when: 
    - inventory_hostname.startswith('master') and inventory_hostname in hostvars[groups['masters'][0]]['nodes_to_add'].stdout

- name: Copy join command
  ansible.builtin.import_tasks: copy-join-command.yaml
  when: 
    - inventory_hostname == groups['masters'][0] or (inventory_hostname.startswith('master') and inventory_hostname in hostvars[groups['masters'][0]]['nodes_to_add'].stdout)

- name: Reupload certs
  ansible.builtin.import_tasks: reupload-certs.yaml
  when: 
    - inventory_hostname == groups['masters'][0]

- name: Join nodes
  ansible.builtin.import_tasks: join-nodes.yaml
  tags: join_nodes
  when: 
    - inventory_hostname == groups['masters'][0] or (inventory_hostname.startswith('master') and inventory_hostname in hostvars[groups['masters'][0]]['nodes_to_add'].stdout)

- name: Scale up worker nodes
  ansible.builtin.include_role:
    name: worker
  when: 
    - inventory_hostname == groups['masters'][0] or (inventory_hostname in hostvars[groups['masters'][0]]['nodes_to_add'].stdout and inventory_hostname.startswith('worker'))

# scale down
- name: Scale down nodes
  ansible.builtin.import_tasks: scale-down.yaml
  when: hostvars[groups['masters'][0]]['nodes_to_remove'].stdout != "[]" and inventory_hostname == groups['masters'][0]
