
- name: Copy taint-label python script
  ansible.builtin.copy:
    src: "taint-label-nodes.py"
    dest: "/opt/kubernetes/taint-label-nodes.py"
    mode: "0644"


- name: taint and label Nodes
  ansible.builtin.shell: |
    export KUBECONFIG=/opt/kubernetes/.kube/config
    export DATA="{{ item }}"
    python3 /opt/kubernetes/taint-label-nodes.py 
  with_items: "{{ values }}"
