- name: New work nodes
  ansible.builtin.debug:
    var: groups['workers']

- name: Remove file (delete file)
  ansible.builtin.file:
    path: "/opt/kubernetes/new_worker_list"
    state: absent


- name: Remove file (delete file)
  ansible.builtin.file:
    path: "/opt/kubernetes/current_worker_list"
    state: absent


- name: Write new worker node list
  lineinfile:
    path: "/opt/kubernetes/new_worker_list"
    line: "{{ item }}"
    create: yes
    state: present
    mode: "0644"
  with_items: "{{ groups['workers'] }}"

- name: Write new worker node list
  ansible.builtin.shell: |
    export KUBECONFIG=/opt/kubernetes/.kube/config
    kubectl get nodes -o json | jq -r '.items[] | select(.metadata.labels["kubernetes.io/hostname"] | startswith("worker-")) | .metadata.name' | sort > /opt/kubernetes/current_worker_list

- name: Compare worker node list
  ansible.builtin.shell: python3 diff.py
  register: worker_nodes_to_add