- name: Print Kubeadm join node command
  ansible.builtin.command: kubeadm token create --print-join-command --ttl 10m
  when: inventory_hostname == groups['masters'][0]
  register: join_command
  tags: create_join_command

# copy the join command to the worker node
- name: Copy the join command to the worker node
  ansible.builtin.copy:
    dest: /opt/token.sh
    content: "{{ hostvars[groups['masters'][0]]['join_command'].stdout }}"
    mode: "0755"
  when: inventory_hostname in groups['workers']
  tags: create_join_command
